### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by rodrigopasc** [mifi/in-app-subscription-example#2]
Hi, how are you?

Can you please share how can I setup my Google account and get the keys? THank you.

**Comment by mifi** [comment]
I don't remember now but i'm sure there's plenty of tutorials on google

**Comment by rodrigopasc** [comment]
But to validate the receipt from Android, I need to setup my Google Service Account? I just need to validate, not to finish the transaction.

**Comment by mifi** [comment]
Yes as far as i remember you need to do that if you want to check if the receipt has been cancelled or not
